#!/usr/bin/env python3

import skilstak.colors as c 
import json
from urllib.request import urlopen

url = "http://api.openweathermap.org/data/2.5/weather?q=Charlotte,uk&appid=d80c42d3cca724b7c9d81266b5d7188c&units=imperial"

html = urlopen(url)
raw = html.read().decode("utf-8")
data = json.loads(raw)

name = (data["name"])
temp = (data["main"]["temp"])

print("In " + name + ", it is " + str(temp) + " degrees.")
